### ISSUE TITLE
Cannot startfpga: (no files matched glob pattern "./user/src/*.bd")

### ISSUE THREAD

**Issue by Pro-A** [Bestduan/fpga_support_plug#1]
i meet some problem like this
[Using Python within TCL script in Vivado 2019.1](https://forums.xilinx.com/t5/Vivado-TCL-Community/Using-Python-within-TCL-script-in-Vivado-2019-1/m-p/982047#M8125)

I wonder if I need to use python2?
(But when I tried to use python 2.7.5, I met some other problem)

I will add screenshot and log later.

**Comment by Pro-A** [comment]
Well, I solved the python problem by add the following lines in tcl script.

```tcl
unset ::env(PYTHONPATH)
unset ::env(PYTHONHOME)

set ::env(PYTHONPATH) "C:/Program Files/Python38/python38.zip:C:/Program Files/Python38/DLLs:C:/Program Files/Python38/lib:C:/Program Files/Python38:C:/Program Files/Python38/lib/site-packages"
set ::env(PYTHONHOME) "C:/Program Files/Python38"
```
But there are still some other problems.

![image](https://user-images.githubusercontent.com/30789285/76308333-82488b00-6305-11ea-98ce-5853aaa5bfc6.png)

I think maybe there are something wrong when initializing the project.

**Comment by Pro-A** [comment]
After comment-out the codes, the script can run now.

![image](https://user-images.githubusercontent.com/30789285/76311302-9d1dfe00-630b-11ea-9d04-37cd52294ef1.png)

![image](https://user-images.githubusercontent.com/30789285/76311288-93949600-630b-11ea-8478-4af93294a626.png)

And I have to recover it after adding IP cores, I think.

**Comment by Bestduan** [comment]
Thank you for your question. This plug-in was not designed for IP and bd at the beginning, while the IP of cortexM3 was added temporarily. I also encountered some problems when I used it today, and I will fix the bug in the near future.In addition, I used version 3.6 of python, with the environment variable added.Finally, if you have any questions, please feel free to ask here.

**Comment by Bestduan** [comment]
In addition, I recommend that you can change the “glob” directive to the “glob-nocomplain /user/Hardware/ src/*.bd”. 
Like:
foreach bd_file [glob -nocomplain ./user/src/*.bd] {
		add_file $bd_file -quiet
}
Because the direct add_file directive cannot be added to the project when bd files are in the src folder.

**Comment by Bestduan** [comment]
The bd design was removed in the updated version 0.1.4.Also, if the python version is 3.6 and the environment variable is not available after it has been set, remove comments about python environment variables from the plug-in's internal scripts
![screenShot.png](https://i.loli.net/2020/03/10/uVN9byimF5pIgar.png)
