### ISSUE TITLE
插件学习

### ISSUE THREAD

**Issue by wangzhankun** [Bestduan/fpga_support_plug#10]
你好，请问可不可以出一个教学视频或者完整的配置教程呀，有很多东西看不明白。
![image](https://user-images.githubusercontent.com/35724924/92355046-0f826600-f116-11ea-8994-e3eb3215cc4d.png)
比方说我的vivado 2019.2下面就没有SDK目录。

**Comment by Bestduan** [comment]
vivado在18版本之后就将vivado和sdk分开来了，SDK等软件需要单独安装vitis，另外这个插件10版本上还没用到SDK的功能可以不添加路径，现在的插件功能只是方便中小工程量的设计，方便创建工程和综合仿真之类。我现在在做12版本，功能加的比较多后期会做一个完整的教程，大概会在年底做完（因为要准备考研）手动狗头
