### ISSUE TITLE
vscode上使用git插件，会一直显示hdl indexing

### ISSUE THREAD

**Issue by qgzln** [Bestduan/fpga_support_plug#14]
![image](https://user-images.githubusercontent.com/47837258/118573591-6f590280-b7b5-11eb-8ff1-98b9ca85cf97.png)
如图

**Comment by Bestduan** [comment]
你的意思是把git插件卸载后就没有这个问题了？这个应该是和你工程下HDL文件数量相关的，你现在工程里有多少HDL文件？文件结构是怎样的

**Comment by qgzln** [comment]
![image](https://user-images.githubusercontent.com/47837258/118575725-b47f3380-b7b9-11eb-9911-ee3730eb0da1.png)类似这种情况，git插件是一直在的，如果我初始化git库就没这个问题。这个图显示即使我这个工程里只有python的git，也会出现这种情况导致git的插件里的文件刷不出来

**Comment by qgzln** [comment]
说错了，是如果不初始化git的存储库就没这个问题

**Comment by Bestduan** [comment]
你现在工程里有多少HDL文件？

**Comment by qgzln** [comment]
40多个

**Comment by qgzln** [comment]
我打开python的工程，也会出现这个情况，只有我不使用git，才正常

**Comment by Bestduan** [comment]
请尝试vscode回溯到1.54版本试试，看是否依然出现这个问题

**Comment by Bestduan** [comment]
是今天才出现的情况吗，我发现又有一个工程之前一直不会出现这情况，今天突然就出现了

**Comment by Bestduan** [comment]
问题找到了，就是HDL文件太多了，就拿cocotb举例，里面有72个HDL文件，又由于是全解析，所以就很解析很长时间，本身又是正则表达式，目前只能用在property文件里声明"HardwareSrc": "./bin",指向需要解析的文件从而不进行HDL的解析，至于为什么不初始化git存储库就没这个问题就想不通了

**Comment by Bestduan** [comment]
vscode每次更新都会出很多问题

**Comment by qgzln** [comment]
上午回完你，就外出了，上午打开的cocotb到现在还在HDL indexing……这个现象出现了一段时间了，一直没来的及跟你反馈，好像只要git开启了才会有这个问题，如果像下图一样就不会出现一直HDL indexing不停的情况
![Uploading image.png…]()

**Comment by qgzln** [comment]
property文件在哪里打开？

**Comment by Bestduan** [comment]
cocotb我是clone下来就有这个问题，property.json是自己生成的

![image](https://user-images.githubusercontent.com/38045864/118614179-122f7200-b7f2-11eb-96f6-bf73212c1485.png)

**Comment by Bestduan** [comment]
建议先版本回退看看

**Comment by qgzln** [comment]
好的

**Comment by Bestduan** [comment]
请问是否已经解决该问题，如果未解决请等待一下版本，我将用webassembly重构整个工程提升速度和效率以支持多文件大工程

**Comment by qgzln** [comment]
等下个版本

**Comment by Bestduan** [comment]
我已经发布新的版本， 在新版本中着重优化了插件内核，解决了一些可能导致卡死的原因，并且新增了一些功能，不知道是否能够解决你的问题。关于状态机的显示将在下个版本，即明年一月发布，届时将会准备全面替代并超越terosHDL。

**Comment by Bestduan** [comment]
三天后我将关闭该issue，届时则认为已经解决你的问题

**Comment by qgzln** [comment]
> 我已经发布新的版本， 在新版本中着重优化了插件内核，解决了一些可能导致卡死的原因，并且新增了一些功能，不知道是否能够解决你的问题。关于状态机的显示将在下个版本，即明年一月发布，届时将会准备全面替代并超越terosHDL。

搞定了，期待
