### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bigxun** [Bestduan/fpga_support_plug#17]
- Issue Type: `Performance`
- Extension Name: `fpga-support`
- Extension Version: `0.1.15`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\DELL\AppData\Local\Temp\sterben.fpga-support-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Bestduan** [comment]
Check to see if the issue has occurred before you ask it.  #15
