### ISSUE TITLE
例化功能模板出错

### ISSUE THREAD

**Issue by xlsjdjdk** [Bestduan/fpga_support_plug#21]
使用例化功能进行模块例化时，最后一个信号末尾有逗号，导致语法错误。
```
pc_reg u_pc_reg(
	//ports
	.clk 		( clk 		),
	.rst 		( rst 		),
	.pc  		( pc  		),
	.ce  		( rom_ce_o  ),
);
```

**Comment by xlsjdjdk** [comment]
能够从顶层跳转的模块如：
```
module pc_reg (
    input  wire clk,
    input  wire rst,
    output reg [`InstAddrBus] pc,
    output reg ce
);
```

无法跳转的模块如：
```
module regfile (
    input  wire clk,
    input  wire rst,
    
    input  wire we,
    input  wire [`RegAddrBus] we_addr,
    input  wire [`RegDataBus] we_data,

    input  wire re1, re2,
    input  wire [`RegAddrBus] re_addr1, re_addr2,
    output  reg [`RegDataBus] re_data1, re_data2
);
```
module mem_wb (
    input  wire clk,
    input  wire rst,

    input  wire [`RegAddrBus] mem_wd,
    input  wire mem_we_reg,
    input  wire [`RegDataBus] mem_we_data,

    output reg [`RegAddrBus] wb_wd,
    output reg wb_we_reg,
    output reg [`RegDataBus] wb_we_data
);
```

**Comment by Bestduan** [comment]
好的，我将在下个版本修复该问题，但最近比较忙要准备考试，可能会拖到年底。

**Comment by Bestduan** [comment]
> 能够从顶层跳转的模块如：
> 
> ```
> module pc_reg (
>     input  wire clk,
>     input  wire rst,
>     output reg [`InstAddrBus] pc,
>     output reg ce
> );
> ```
> 
> 无法跳转的模块如：
> 
> ```
> module regfile (
>     input  wire clk,
>     input  wire rst,
>     
>     input  wire we,
>     input  wire [`RegAddrBus] we_addr,
>     input  wire [`RegDataBus] we_data,
> 
>     input  wire re1, re2,
>     input  wire [`RegAddrBus] re_addr1, re_addr2,
>     output  reg [`RegDataBus] re_data1, re_data2
> );
> ```
> 
> ```
> module mem_wb (
>     input  wire clk,
>     input  wire rst,
> 
>     input  wire [`RegAddrBus] mem_wd,
>     input  wire mem_we_reg,
>     input  wire [`RegDataBus] mem_we_data,
> 
>     output reg [`RegAddrBus] wb_wd,
>     output reg wb_we_reg,
>     output reg [`RegDataBus] wb_we_data
> );
> ```

我这边是能直接跳转的，可能是响应时间有点长，你使用ctrl + 左击的方式等待响应后可跳转，因为查找源是一个比较复杂的过程尤其是在文件比较多的时候。如还不行请回复。

**Comment by Bestduan** [comment]
测试代码如下
```
module regfile (
    input  wire clk,
    input  wire rst,
    
    input  wire we,
    input  wire [`RegAddrBus] we_addr,
    input  wire [`RegDataBus] we_data,

    input  wire re1, re2,
    input  wire [`RegAddrBus] re_addr1, re_addr2,
    output  reg [`RegDataBus] re_data1, re_data2
);

wire [`RegAddrBus] 	wb_wd;
wire               	wb_we_reg;
wire [`RegDataBus] 	wb_we_data;

mem_wb u_mem_wb(
	//ports
	.clk         		( clk         		),
	.rst         		( rst         		),
	.mem_wd      		( mem_wd      		),
	.mem_we_reg  		( mem_we_reg  		),
	.mem_we_data 		( mem_we_data 		),
	.wb_wd       		( wb_wd       		),
	.wb_we_reg   		( wb_we_reg   		),
	.wb_we_data  		( wb_we_data  		)
);


endmodule

module mem_wb (
    input  wire clk,
    input  wire rst,

    input  wire [`RegAddrBus] mem_wd,
    input  wire mem_we_reg,
    input  wire [`RegDataBus] mem_we_data,

    output reg [`RegAddrBus] wb_wd,
    output reg wb_we_reg,
    output reg [`RegDataBus] wb_we_data
);

wire [`RegDataBus] 	re_data1;
wire               	re_data2;

regfile u_regfile(
	//ports
	.clk      		( clk      		),
	.rst      		( rst      		),
	.we       		( we       		),
	.we_addr  		( we_addr  		),
	.we_data  		( we_data  		),
	.re1      		( re1      		),
	.re2      		( re2      		),
	.re_addr1 		( re_addr1 		),
	.re_addr2 		( re_addr2 		),
	.re_data1 		( re_data1 		),
	.re_data2 		( re_data2 		)
);


endmodule
```
![效果图](https://i.loli.net/2021/08/31/8hmxldSQT4RM7LZ.png)

**Comment by Bestduan** [comment]
已解决
