### ISSUE TITLE
打开文件夹时出错

### ISSUE THREAD

**Issue by qgzln** [Bestduan/fpga_support_plug#23]
![image](https://user-images.githubusercontent.com/47837258/131461517-8b97b7d6-eb70-4f9a-9763-b1b5d4bc4ba7.png)

**Comment by Bestduan** [comment]
说明该文件夹下文件太多，超出设置中的limit，可以在setting中的 `PRJ.file.limit.number` 下更改所能支持的极限个数。但文件个数越多初始化时间也就越长，请设置合适的极限个数。

**Comment by qgzln** [comment]
ok
