### ISSUE TITLE
README file in English for better adoption

### ISSUE THREAD

**Issue by EternalCodeMonkey** [Bestduan/fpga_support_plug#3]
Just as a suggestion, but you might want to include an English version of the main `README.md` file.  It might help increase the number of user installs the extension gets in VS Code.

Likewise, having the `CHANGELOG.md` contain the project revision information might be something worth looking into.

Here's my shot at the translation and changelog (rename to remove the `*.txt` extension):
* [README.md.txt](https://github.com/Bestduan/fpga_support_plug/files/4457633/README.md.txt)
* [CHANGELOG.md.txt](https://github.com/Bestduan/fpga_support_plug/files/4457632/CHANGELOG.md.txt)

**Comment by Bestduan** [comment]
Thanks for your advice.I will change my readme file as soon as possible
