### ISSUE TITLE
综合功能无法综合testbench程序

### ISSUE THREAD

**Issue by Xiao-Minger** [Bestduan/fpga_support_plug#30]
综合testbench报错：
ERROR: syntax error, unexpected '#'
![image](https://user-images.githubusercontent.com/81314168/146592212-50157cd7-03cf-4cb7-8375-2990623dc24f.png)

综合调用的模块则成功
![image](https://user-images.githubusercontent.com/81314168/146592239-f90b467e-7457-4418-988a-a739b6dd2559.png)

**Comment by Bestduan** [comment]
这是采用的yosys综合器所导致的，yosys本身不支持仿真级语法。

**Comment by Xiao-Minger** [comment]
那有没有方法能实现多个模块的综合

**Comment by Bestduan** [comment]
现在的版本应该是能实现多个模块的，但是功能并不完善，还有bug在里面，最近在做多模块综合并显示的功能，将在1.20版发布。
