### ISSUE TITLE
Need change "run.tcl" to "Run.tcl" in startfpga command

### ISSUE THREAD

**Issue by Pro-A** [Bestduan/fpga_support_plug#4]
If we have an existing project, 'startFPGA' seems to run 'Run.tcl' by:
```tcl
source ${HOME}/.vscode/extensions/sterben.fpga-support-0.1.10/src/.TOOL/Xilinx/Script/Xilinx_TCL/Vivado/run.tcl
```
We can execute it successfuly on Windows since Windows is case insensitive.
But Linux is case sensitive, so it cannot find file "run.tcl".

This problem can be easily solved by modifying the line in file:
${HOME}/.vscode/extensions/sterben.fpga-support-0.1.10/src/.TOOL/.Script/start.py

**Comment by Bestduan** [comment]
Thanks for your advice, I will fix this problem in the next version
