### ISSUE TITLE
Succeed using module pyperclip to control clipboard

### ISSUE THREAD

**Issue by proarz** [Bestduan/fpga_support_plug#5]
## Description
I tried using pyperclip to copy instance to clipboard, and succeeded in macOS.

I am not sure if it makes sense on other os. I will try it later.

## Environment
- OS: macOS 10.15.4
- Python: 3.7.7

## Solution
Import the module:
```python
import pyperclip
```
Use a string to record data, for example, ```instance_data```.
And then just use
```python
pyperclip.copy(instance_data)
```
to copy the string to clipboard.

**Comment by Bestduan** [comment]
I simply tested that this function is valid in win, but it can only copy the part of the example, the part of the port is not copied in.
![screenShot.png](https://i.loli.net/2020/04/27/Q9z4npqJoSiBfFw.png)
![screenShot.png](https://i.loli.net/2020/04/27/srzmuZDOTLX4EUQ.png)
![screenShot.png](https://i.loli.net/2020/04/27/newl431oV6j5Jha.png)

**Comment by Pro-A** [comment]
> I simply tested that this function is valid in win, but it can only copy the part of the example, the part of the port is not copied in.
> ![screenShot.png](https://camo.githubusercontent.com/4490049b2988b387078f5f224fddde92037c4c77/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f32372f51397a346e70714a6f5369426646772e706e67)
> ![screenShot.png](https://camo.githubusercontent.com/d103cb0aa43544d8045f29c4a0e8c4292fe33b8b/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f32372f73727a6d755a444f544c58344555512e706e67)
> ![screenShot.png](https://camo.githubusercontent.com/8428e79072c766367794cce928832a934bb99339/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f32372f6e65776c3433316f56366a354a68612e706e67)

I use one string to store the whole data.
Maybe you can also try this.
```python
def writeTestBench(input_file):
    """ write testbench to file """
    with open(input_file, 'rb') as f:
        f_info = chardet.detect(f.read())
        f_encoding = f_info['encoding']
    with open(input_file, encoding=f_encoding) as inFile:
        inText = inFile.read()

    # removed comment,task,function
    inText = delComment(inText)
    inText = delBlock(inText)

    # moduel ... endmodule  #
    moPos_begin = re.search(r'(\b|^)module\b', inText).end()
    moPos_end = re.search(r'\bendmodule\b', inText).start()
    inText = inText[moPos_begin:moPos_end]

    name = findName(inText)
    paraList = paraDeclare(inText, 'parameter')
    paraDec, paraDef = formatPara(paraList)

    ioPadAttr = ['input', 'output', 'inout']
    input = portDeclare(inText, ioPadAttr[0])
    output = portDeclare(inText, ioPadAttr[1])
    inout = portDeclare(inText, ioPadAttr[2])

    portList = formatPort([input, output, inout])
    input = formatDeclare(input, 'reg')
    output = formatDeclare(output, 'wire')
    inout = formatDeclare(inout, 'wire')

    # write Instance
    instance_data = ""
    # module_parameter_port_list
    if (paraDec != ''):
        print("// %s Parameters\n%s\n" % (name, paraDec))
        instance_data += "// " + name + " Parameters\n" + paraDec + "\n"

    # list_of_port_declarations
    print("// %s Inputs\n%s\n" % (name, input))
    instance_data += "// " + name + " Inputs\n" + input + "\n"
    print("// %s Outputs\n%s\n" % (name, output))
    instance_data += "// " + name + " Outputs\n" + output + "\n"
    if (inout != ''):
        print("// %s Bidirs\n%s\n" % (name, inout))
        instance_data += "// " + name + " Bidirs\n" + inout + "\n"

    print("%s %s U_%s (\n%s\n);" % (name, paraDef, name, portList))
    instance_data += name + " " + paraDef + " U_" + name + "_0 (\n" + portList + "\n);"
    pyperclip.copy(instance_data)
```
